apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 6
  selector:
    matchLabels:
      run: my-app
  template:
    metadata:
      labels:
        run: my-app
    spec:
      containers:
      - name: my-container
        image: gcr.io/google-samples/hello-app:2.0
        env:
          - name: SECRET_USERNAME
            valueFrom:
              secretKeyRef:
                name: top-secret
                key: username
          - name: SECRET_PASSWORD
            valueFrom:
              secretKeyRef:
                name: top-secret
                key: password